version: '2'

services:
  monacoin:
    extends:
      file: docker-compose.tmpl.yml
      service: bitcoin-base-mainnet

  monacoin-testnet:
    extends:
      file: docker-compose.tmpl.yml
      service: bitcoin-base-testnet

  indexd:
    extends:
      file: docker-compose.tmpl.yml
      service: indexd-base-mainnet

  indexd-testnet:
    extends:
      file: docker-compose.tmpl.yml
      service: indexd-base-testnet

  counterparty:
    extends:
      file: docker-compose.tmpl.yml
      service: counterparty-base-mainnet
    links:
      - monacoin

  counterparty-testnet:
    extends:
      file: docker-compose.tmpl.yml
      service: counterparty-base-testnet
    links:
      - monacoin-testnet

  mongodb:
    extends:
      file: docker-compose.tmpl.yml
      service: mongodb-base

  redis:
    extends:
      file: docker-compose.tmpl.yml
      service: redis-base

  ipfs:
    extends:
      file: docker-compose.tmpl.yml
      service: ipfs-base

#  armory-utxsvr:
#    extends:
#      file: docker-compose.tmpl.yml
#      service: armory-utxsvr-base-mainnet
#    links:
#      - bitcoin
#
#  armory-utxsvr-testnet:
#    extends:
#      file: docker-compose.tmpl.yml
#      service: armory-utxsvr-base-testnet
#    links:
#      - bitcoin-testnet

  counterblock:
    extends:
      file: docker-compose.tmpl.yml
      service: counterblock-base-mainnet
    links:
      - monacoin
      - counterparty
      - mongodb
      - redis
#      - armory-utxsvr

  counterblock-testnet:
    extends:
      file: docker-compose.tmpl.yml
      service: counterblock-base-testnet
    links:
      - monacoin-testnet
      - counterparty-testnet
      - mongodb
      - redis
#      - armory-utxsvr-testnet

  counterwallet:
    extends:
      file: docker-compose.tmpl.yml
      service: counterwallet-base
    links:
      - redis
      - counterblock
      - counterblock-testnet

volumes:
  bitcoin-data:
  indexd-data:
  counterparty-data:
  counterblock-data:
  mongodb-data:
  ipfs-data:
#  armory-data:
