on:
  schedule:
    - cron:  '0 0 * * 2'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Post netlify build hook
      run: |
        curl -H "Content-Type: application/json" --data '{"build": true}' -X POST ${{ secrets.DOCKER_HUB_WEBHOOK_URL }}
